general:
    debug : False
    instance_name : "AXIA Search"

search:
    language: "all"

server:
    port : 11111
    bind_address : 127.0.0.1
    secret_key : "cRfTjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D*G-KaPdSgVkYp3s6v9y/B?E(H+MbQeThWmZq4t7w!z%C"
    base_url : False
    http_protocol_version : "1.0"

ui:
    static_path : ""
    templates_path : ""
    default_theme : oscar

preferences:
    lock: []

outgoing:
    request_timeout : 1.0 # seconds
    useragent_suffix : ""

engines:
  - name : general dummy
    engine : dummy
    categories : general
    shortcut : gd

  - name : dummy dummy
    engine : dummy
    categories : dummy
    shortcut : dd

locales:
    en : English
    hu : Magyar

doi_resolvers :
  oadoi.org : 'https://oadoi.org/'
  doi.org : 'https://doi.org/'
  doai.io  : 'https://dissem.in/'
  sci-hub.tw : 'https://sci-hub.tw/'

default_doi_resolver : 'sci-hub.tw'
